#checkov:skip:CKV2_GHA_1:Comment
name: Build Release
run-name: Release - ${{ gitea.event.repository.name }}

on:
  # release:
  #   types: [published]
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Bundle and Release
    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          ref: ${{ gitea.ref }}
          fetch-depth: 0

      - name: Setup StagToolkit
        uses: ./.gitea/setup
        with:
          godot-version: null
          cross-compile: true
          toolkit-path: '.'
          import-assets: false

      - name: Build and Bundle
        id: build-bundle
        run: make bundle

      # https://github.com/softprops/action-gh-release
      # - name: Upload Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: build/addon_StagToolkit.zip
      #     generate_release_notes: true

      - name: Upload Release Artifact
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: built-toolkit
          path: build/addon_StagToolkit.zip
          if-no-files-found: error
          retention-days: 30
