[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-pthread", # Only for threading support
    "-C", "target-feature=+atomics", # Only for threading support
    "-C", "link-args=-sSIDE_MODULE=2",
    "-Zlink-native-libraries=no",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
]
