#checkov:skip:CKV2_GHA_1:Comment
name: Build and Deploy Docs
run-name: Docs - ${{ github.event.repository.name }}

on:
    # pull_request:
    #   types:
    #     - opened
    #     - reopened
    #     - closed
    #     - synchronize
    push:
        tags-ignore:
            - "**"
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    pages:
        runs-on: ubuntu-slim
        name: Build Docs
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            id-token: write # to verify the deployment originates from an appropriate source
            contents: read
            pages: write # to deploy to Pages

        steps:
            - name: Clone
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 1

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: "pyproject.toml"

            - name: Install Python Dependencies
              run: |
                  pip install -r pyproject.toml

            - name: Setup StagToolkit
              uses: ./.gitea/composite/setup
              with:
                  cross-compile: false
                  toolkit-path: "."
                  import-assets: false

            - name: Generate Documentation
              shell: bash
              run: |
                  cd sphinx && ./build.sh

            - name: Deploy to GitHub Pages
              id: deployment
              uses: sphinx-notes/pages@v3
              with:
                  documentation_path: ./sphinx/
                  requirements_path: pyproject.toml
                  python_version: 3.14
                  pyproject_extras: docs
                  checkout: false
                  publish: true
